export const Action_Types = {
    'ADD_TO_CART': 'ADD_TO_CART',
    'REMOVE_FROM_CART': 'REMOVE_FROM_CART',
    'SET_PRODUCT': 'SET_PRODUCT',
    'INCREMENT_QUANTITY':'INCREMENT_QUANTITY',
    'DECREMENT_QUANTITY': 'DECREMENT_QUANTITY'
}